// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "API Title",
	Description:      "API description",
	SwaggerTemplate:  `{
		"openapi": "3.0.0",
		"info": {
			"description": "{{escape .Description}}",
			"title": "{{.Title}}",
			"version": "{{.Version}}"
		},
		"servers": [
			{
				"url": "{{.Host}}"
			}
		],
		"paths": {}
	}`,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
