version: "3"

services:
  postgres:
    image: "postgres:12-alpine"
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: simple_bank
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/postgres_db_simple_bank_v2.sql:/docker-entrypoint-initdb.d/create_tables.sql
